services:


  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tumelo
      - MONGO_INITDB_ROOT_PASSWORD=tumelo

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=tumelo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=tumelo

volumes:
    mongo:
      driver: local