spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:6000/customer-service
    username: tumelosizani
    password: tumelosizani
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8086

application:
  config:
    account-url: "http://localhost:8080"