spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:6000/customer-service

  jpa:
    hibernate:
      ddl-auto: create-drop

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8090