spring:
  application:
    name: account-service

  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6000/account-service
    username: tumelosizani
    password: tumelosizani
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

application:
  config:
    transaction-url: "http://localhost:8085"
    customer-url: "http://localhost:8086"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

interest:
  rate: 0.1