server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # Automatically create and drop the schema
    database-platform: org.hibernate.dialect.H2Dialect

  application:
    name: account-service

  config:
    import: optional:configserver:http://localhost:8888